version: "3.9"

services:
  backend:
    image: ghcr.io/OWNER/REPO/backend:latest # will be replaced with the correct tag in CI
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/receipts
    volumes:
      # it's a single file, we need to use a direct bind mount
      - /opt/ai-agent-vision/conf/.env:/app/.env
      - backend-uploads:/app/uploads

  ui:
    image: ghcr.io/OWNER/REPO/ui:latest # will be replaced with the correct tag in CI
    container_name: ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    restart: unless-stopped
    command: ["--replSet", "rs0"]
    environment:
      - MONGO_INITDB_DATABASE=receipts # change this if not using the default database
    container_name: mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-init-replica:
    # Initilaize the MongoDB replica set, required for change streams to work
    image: mongo:7
    depends_on:
      - mongo
    entrypoint:
      [
        "bash",
        "-c",
        'sleep 5 && mongosh --host mongo --eval ''try { rs.initiate({_id: "rs0", members: [{ _id: 0, host: "mongo:27017" }]}) } catch(e) { print(e) }''',
      ]

  mongo-backup:
    image: ghcr.io/OWNER/REPO/mongo-backup:latest # replace with the correct tag in CI
    container_name: mongo-backup
    depends_on:
      - mongo
    volumes:
      - mongo-backup:/backup
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

volumes:
  mongo-data:
  backend-uploads:
  mongo-backup:
