version: "3.9"

services:
  backend:
    image: ghcr.io/OWNER/REPO/backend:latest # will be replaced with the correct tag in CI
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/receipts
    # Uncomment the next lines to map an external .env file
    # volumes:
    #   - ./path/to/your/.env:/app/.env

  ui:
    image: ghcr.io/OWNER/REPO/ui:latest # will be replaced with the correct tag in CI
    container_name: ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      # Uncomment the next line to map a local folder for MongoDB data persistence
      # - ./mongo-data:/data/db

volumes:
  mongo-data:
