version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/ai-agent-vision:cached
      - ~/.aws:/home/vscode/.aws:cached # Mount AWS credentials for Amazon Q
    command: sleep infinity
    network_mode: service:mongodb
    environment:
      - MONGODB_URI=mongodb://localhost:27017
      - MONGODB_DATABASE=receipts
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}

  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0"]
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=receipts
    # Ensure MongoDB starts automatically
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-init-replica:
    image: mongo:latest
    depends_on:
      - mongodb
    entrypoint:
      [
        "bash",
        "-c",
        'sleep 5 && mongosh --host mongodb --eval ''try { rs.initiate({_id: "rs0", members: [{ _id: 0, host: "mongodb:27017" }]}) } catch(e) { print(e) }''',
      ]

volumes:
  mongodb-data:
